export const reassignCandidates = [
    {
        id: 'ENG-104',
        name: 'Иван Петров',
        icon: '👷‍♂️',
        transport: 'Lada Largus',
        load: '3/5 заявок',
        deviation: '+1.8 км (+8 мин)',
        stock: 'В наличии (2 шт)',
        stockOk: true,
        isOptimal: true,
        reason: null,
        buttonText: 'Назначить мастера',
        disabled: false,
    },
    {
        id: 'ENG-108',
        name: 'Михаил Сидоров',
        icon: '👷‍♂️',
        transport: 'Gazelle',
        load: '4/5 заявок',
        deviation: '+5.4 км (+22 мин)',
        stock: 'В наличии (1 шт)',
        stockOk: true,
        isOptimal: false,
        reason: null,
        buttonText: 'Выбрать',
        disabled: false,
    },
    {
        id: 'ENG-111',
        name: 'Дмитрий Кузнецов',
        icon: '🚶‍♂️',
        transport: 'Пеший',
        load: null,
        deviation: null,
        stock: null,
        stockOk: false,
        isOptimal: false,
        reason: '⚠️ Нет нужного роутера в наличии • Отклонение +12 км',
        buttonText: 'Не подходит',
        disabled: true,
    },
]